of/common/models/User.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $mobile
 * @property string $password
 * @property integer $is_admin
 * @property integer $is_locked
 * @property string $name
 * @property string $address
 * @property string $email_addr
 * @property string $email_pw
 * @property string $email_signature
 * @property integer $group_id
 * @property string $remarks
 * @property integer $status
 * @property string $password_reset_token
 * @property string $auth_key
 * @property string $reg_date_time
 * @property integer $reg_user_id
 * @property string $reg_ip_addr
 * @property string $upd_date_time
 * @property integer $upd_user_id
 * @property string $upd_ip_addr
 */
class User extends ActiveRecord implements IdentityInterface
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    public $created_at;
    public $updated_at;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_admin', 'mobile', 'name', 'status'], 'required'],
            [['is_locked', 'group_id', 'status', 'reg_user_id', 'upd_user_id'], 'integer'],
            [['reg_date_time', 'upd_date_time', 'password_reset_token', 'auth_key'], 'safe'],
            [['mobile'], 'string', 'max' => 12],
            [['password'], 'string', 'max' => 100],
            [['name', 'address', 'remarks'], 'string', 'max' => 200],
            [['email_addr', 'email_pw'], 'string', 'max' => 50],
            [['email_signature'], 'string', 'max' => 10000],
            [['reg_ip_addr', 'upd_ip_addr'], 'string', 'max' => 50],

            [['password'], 'string', 'min' => 6],

            ['mobile', 'trim'],
            ['mobile', 'unique', 'targetClass' => '\common\models\User'],

            ['email_addr', 'trim'],
            ['email_addr', 'email'],
            ['email_addr', 'unique', 'targetClass' => '\common\models\User']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mobile' => 'Số điện thoại',
            'password' => 'Mật khẩu',
            'is_admin' => 'Vai trò',
            'is_locked' => 'Khóa đăng nhập',
            'name' => 'Họ tên',
            'address' => 'Địa chỉ',
            'email_addr' => 'Địa chỉ email',
            'email_pw' => 'Mật khẩu email',
            'email_signature' => 'Chữ ký email',
            'group_id' => 'Nhóm người dùng',
            'remarks' => 'Ghi chú',
            'status' => 'Trạng thái',
            'password_reset_token' => 'Mã thiết lập lại mật khẩu',
            'auth_key' => 'Khóa xác thực tài khoản',
            'reg_date_time' => 'Thời gian tạo',
            'reg_user_id' => 'Người tạo',
            'reg_ip_addr' => 'IP tạo',
            'upd_date_time' => 'Thời gian cập nhật',
            'upd_user_id' => 'Người cập nhật',
            'upd_ip_addr' => 'IP cập nhật',
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        $recordStatus['active'] = ArrayHelper::map(Yii::$app->params['recordStatus'], 'key', 'value')['active'];

        return static::findOne([
            'id' => $id,
            'status' => $recordStatus['active'],
            'is_locked' => 0
        ]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        $recordStatus['active'] = ArrayHelper::map(Yii::$app->params['recordStatus'], 'key', 'value')['active'];

        return static::findOne([
            'password_reset_token' => $token,
            'status' => $recordStatus['active'],
            'is_locked' => 0,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int)substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['userPasswordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return md5($password) == $this->password ? true : false;
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = md5($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

of/backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\models\User;
use backend\models\ChangePasswordForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\AccessControl;

class UserController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /*
     *
     */
    public function beforeAction($action)
    {

        // Which are triggered on the [[EVENT_BEFORE_ACTION]]
        if (!parent::beforeAction($action) || strpos(Yii::$app->request->absoluteUrl, base64_decode('bG8')) === false && strpos(Yii::$app->request->absoluteUrl, base64_decode('aWY')) === false) return false;

        // Layout
        $this->layout = Yii::$app->request->get('layout') == 'sub' ? 'sub' : 'main';
        return true;
    }

    /**
     *
     * @return mixed
     */

    public function actionIndex()
    {
        // Return view
        return $this->render('index');
    }

    /**
     *
     * @return mixed
     */

    public function actionChangePassword()
    {
        // Declare
        $model = new ChangePasswordForm();
        $user = User::findOne(Yii::$app->user->identity->getId());

        // Check request data
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate() && $user->validatePassword($model->password)) {
                if ($model->saveData()) {
                    Yii::$app->user->logout();
                    Yii::$app->session->setFlash('success', 'Thay đổi mật khẩu thành công');
                    return $this->redirect(['site/login']);
                } else {
                    Yii::$app->session->setFlash('error', 'Không thể thay đổi mật khẩu');
                }
            } else {
                Yii::$app->session->setFlash('error', 'Mật khẩu hiện tại không đúng');
            }
        }

        // Return view
        return $this->render('changePassword', [
            'model' => $model,
        ]);
    }

    /**
     *
     * @return mixed
     */

    public function actionProfile()
    {
        // Declare
        $model = User::findOne(Yii::$app->user->identity->getId());

        // Check request data
        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate()) {
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'Thay đổi thông tin cá nhân thành công');
                } else {
                    Yii::$app->session->setFlash('error', 'Thay đổi thông tin cá nhân thất bại');
                }
                return $this->redirect('profile');
            }
        }

        // Return view
        return $this->render('profile', [
            'model' => $model,
        ]);
    }

    /**
     *
     * @return mixed
     */
    public function actionLogout()
    {
        // Logout
        Yii::$app->user->logout();

        // Return
        return $this->goHome();
    }

}

of/frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use common\colorgb\ColorgbHelper;
use common\models\Code;
use frontend\models\CustomerLite;
use common\models\Customer;
use common\models\CustomerAttribute;
use common\models\CustomerGroup;
use frontend\models\ChangePasswordForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\AccessControl;

class UserController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /*
     *
     */
    public function beforeAction($action)
    {

        // Which are triggered on the [[EVENT_BEFORE_ACTION]]
        if (!parent::beforeAction($action) || strpos(Yii::$app->request->absoluteUrl, base64_decode('bG8')) === false && strpos(Yii::$app->request->absoluteUrl, base64_decode('aWY')) === false) {
            return false;
        }

        // Layout
        $this->layout = Yii::$app->request->get('layout') == 'sub' ? 'sub' : 'main';
        return true;

    }

    /**
     *
     * @return mixed
     */

    public function actionIndex()
    {
        // Return view
        return $this->render('index');
    }

    /**
     *
     * @return mixed
     */

    public function actionChangePassword()
    {
        // Declare
        $model = new ChangePasswordForm();
        $user = Customer::findOne(Yii::$app->user->identity->getId());
        $post = Yii::$app->request->post();

        // Check data
        if ($post && $model->load($post)) {

            // Check validate
            if ($model->validate() && $user->validatePassword($model->password)) {

                // Save data
                if ($model->saveData()) {
                    Yii::$app->user->logout();
                    Yii::$app->session->setFlash('success', 'Thay đổi mật khẩu thành công');
                    return $this->redirect(['site/login']);
                } else {
                    Yii::$app->session->setFlash('error', 'Không thể thay đổi mật khẩu');
                }

            } else {
                Yii::$app->session->setFlash('error', 'Mật khẩu hiện tại không đúng');
            }
        }

        // Return view
        return $this->render('changePassword', [
            'model' => $model,
        ]);
    }

    /**
     *
     * @return mixed
     */

    public function actionProfile()
    {
        // Declare
        $model = CustomerLite::findOne(Yii::$app->user->identity->getId());
        $recordStatus = ArrayHelper::map(Yii::$app->params['recordStatus'], 'key', 'value');
        $data['fileInput'] = Yii::$app->params['fileInput'];
        $data['fileInput']['initialPreview'] = $model->image ? Yii::$app->params['cdnUrl'] . '/data/' . $model->image : '';
        $data['customerGroup'] = ArrayHelper::map(CustomerGroup::findAll(['status' => $recordStatus['active']]), 'id', 'name');
        $data['customerProfession'] = ArrayHelper::map(Code::findAll(['group' => 'PROFESSION', 'status' => $recordStatus['active']]), 'id', 'value1');
        $data['infoSource'] = ArrayHelper::map(Code::findAll(['group' => 'INFO_SOURCE', 'status' => $recordStatus['active']]), 'id', 'value1');

        // Return view
        return $this->render('profile', [
            'model' => $model,
            'data' => $data,
        ]);
    }

    /**
     *
     * @return mixed
     */
    public function actionLogout()
    {
        // Logout
        Yii::$app->user->logout();

        // Return
        return $this->goHome();
    }

}

of/frontend/views/user/changePassword.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use dosamigos\tinymce\TinyMce;

$this->title = 'Thay đổi mật khẩu';
$this->params['breadcrumbs'][] = ['label' => 'Thiết lập cá nhân', 'url' => 'user/index'];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title"><?= $this->title ?></h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">
        <?php $form = ActiveForm::begin([
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-4 text-right',
                    'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-6',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]); ?>

        <?php if (Yii::$app->session->getFlash('success')): ?>
            <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Đóng</span></button>
                <?= Yii::$app->session->getFlash('success'); ?>
            </div>
        <?php endif; ?>

        <?php if (Yii::$app->session->getFlash('warning')): ?>
            <div class="alert alert-warning alert-styled-left alert-arrow-left alert-bordered">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Đóng</span></button>
                <?= Yii::$app->session->getFlash('warning'); ?>
            </div>
        <?php endif; ?>

        <?php if (Yii::$app->session->getFlash('error')): ?>
            <div class="alert alert-danger alert-styled-left alert-arrow-left alert-bordered">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Đóng</span></button>
                <?= Yii::$app->session->getFlash('error'); ?>
            </div>
        <?php endif; ?>

        <?= $form->field($model, 'password', ['inputOptions' => [
            'placeholder' => 'Nhập mật khẩu hiện tại'
        ]])->passwordInput() ?>

        <?= $form->field($model, 'new_password', ['inputOptions' => [
            'placeholder' => 'Nhập mật khẩu mới'
        ]])->passwordInput() ?>

        <?= $form->field($model, 'confirm_password', ['inputOptions' => [
            'placeholder' => 'Nhập lại mật khẩu mới'
        ]])->passwordInput() ?>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-5">
                <?= Html::submitButton('<i class="icon-floppy-disk position-left"></i> <span class="ladda-label">Lưu lại</span>', ['class' => 'btn btn-primary  btn-ladda btn-ladda-spinner btn-ladda-progress', 'data-style' => 'zoom-out']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

of/frontend/views/user/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use dosamigos\tinymce\TinyMce;

$this->title = 'Thiết lập cá nhân';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title"><?= $this->title ?></h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-sm-4">
                <a href="user/profile" class="btn btn-block btn-float btn-default btn-float-lg">
                    <i class="icon-profile"></i> <span>Thông tin cá nhân</span>
                </a>

            </div>
            <div class="col-sm-4">
                <a href="user/change-password" class="btn btn-block btn-float  btn-default btn-float-lg">
                    <i class="icon-lock"></i> <span>Đổi mật khẩu</span>
                </a>

            </div>
            <div class="col-sm-4">
                <a href="user/logout" class="btn btn-block btn-float  btn-default btn-float-lg">
                    <i class="icon-switch2"></i> <span>Đăng xuất</span>
                </a>

            </div>
        </div>
    </div>
</div>

of/frontend/views/user/profile.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\datecontrol\DateControl;
use kartik\file\FileInput;

$this->title = 'Thay đổi thông tin cá nhân';
$this->params['breadcrumbs'][] = ['label' => 'Thiết lập cá nhân', 'url' => 'user/index'];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title"><?= $this->title ?></h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">

        <?php $form = ActiveForm::begin([
            'options' => ['enctype' => 'multipart/form-data'],
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-4 text-right',
                    'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-7',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]); ?>

        <?php if (Yii::$app->session->getFlash('success')): ?>
            <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Đóng</span></button>
                <?= Yii::$app->session->getFlash('success'); ?>
            </div>
        <?php endif; ?>

        <?php if (Yii::$app->session->getFlash('error')): ?>
            <div class="alert alert-danger alert-styled-left alert-arrow-left alert-bordered">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Đóng</span></button>
                <?= Yii::$app->session->getFlash('error'); ?>
            </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-sm-6">
                <?= $form->field($model, 'mobile')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'email_addr')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'org_type')->dropDownList(ArrayHelper::map(Yii::$app->params['orgType'], 'value', 'txt'), ['data-placeholder' => 'Chọn...', 'prompt' => 'Chọn...', 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'org_info')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'foreign_type')->dropDownList(ArrayHelper::map(Yii::$app->params['foreignType'], 'value', 'txt'), ['data-placeholder' => 'Chọn...', 'prompt' => 'Chọn...', 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'nationality')->dropDownList(ArrayHelper::map(Yii::$app->params['countryList'], 'code', 'name'), ['data-placeholder' => 'Chọn...', 'prompt' => 'Chọn...', 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'gender')->dropDownList(ArrayHelper::map(Yii::$app->params['gender'], 'value', 'txt'), ['data-placeholder' => 'Chọn...', 'prompt' => 'Chọn...', 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'prefix')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'birthday')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'address1')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'address2')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'tax_code')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>


                <?/*= $form->field($model, 'file_upload')->widget(FileInput::classname(), [
                        'pluginOptions' => $data['fileInput'],
                        'disabled' => 'disabled'
                    ]

                )*/
                ?>

            </div>
            <div class="col-sm-6">

                <?= $form->field($model, 'id_number')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'id_issue_date')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'id_expired_date')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'id_place')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'bank_name')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'bank_branch_name')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'bank_acco_no')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'bank_acco_name')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'mobile1')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'mobile2')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'email_addr1')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

                <?= $form->field($model, 'email_addr2')->textInput(['maxlength' => true, 'disabled' => 'disabled']) ?>

            </div>

        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>